learning_rate: 0.005
batch_size: 128 #256
gpu_id: '0' 
# sim_type: "leiden" 

field_separator: "\t"
seq_separator: " " 
USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id 
# RATING_FIELD: rating 
TIME_FIELD: timestamp 

load_col: ~
    # inter: [session_id, item_id, timestamp, community_id, user_id]
# benchmark_filename: ["train", "test"]

# NEG_PREFIX: neg_ 
# LABEL_FIELD: label 
# ITEM_LIST_LENGTH_FIELD: item_length 
# LIST_SUFFIX: _list 
MAX_ITEM_LIST_LENGTH: 50 
# POSITION_FIELD: position_id 

min_user_inter_num: 0
min_item_inter_num: 0

# training settings
epochs: 50
learner: adam 
neg_sampling: ~
train_neg_sample_args: ~
eval_step: 1 
stopping_step: 10 

# benchmark_filename: ["train", "valid", "test"]
# alias_of_item_id: ["item_id_list"]

# evalution settings
eval_args:
#    group_by: None
   split: {'RS': [0.8,0.1,0.1]}
#    split: {'LS': 'valid_and_test'}
   order: TO
   mode: full
   group_by: user

metrics: ["MRR","NDCG","Hit","Recall"] 
valid_metric: MRR@10 
# weight_decay: 0
topk: [5, 10, 20, 50]

# directory setting
log_root: "./log/"
data_path: "./processed_data/"
checkpoint_dir: "./saved/reddit/"

tau: 1
# contrast: 'us_x'
# sim: 'dot'

# hidden_dropout_prob: 0.5
# attn_dropout_prob: 0.5