learning_rate: 0.01 # 0.01, 0.005, 0.001
batch_size: 256 # 512,
gpu_id: '0' 

field_separator: "\t"
seq_separator: " " 
USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id 
TIME_FIELD: timestamp 

load_col: ~
MAX_ITEM_LIST_LENGTH: 50 

min_user_inter_num: 0
min_item_inter_num: 0

# training settings
epochs: 50
learner: adam 
neg_sampling: ~
train_neg_sample_args: ~
eval_step: 1 
stopping_step: 10 

# evalution settings
eval_args:
   split: {'RS': [0.8,0.1,0.1]}
   order: TO
   mode: full
   group_by: user

metrics: ["MRR","NDCG","Hit","Recall"] 
valid_metric: MRR@10 
topk: [5, 10, 20, 50]

# directory setting
log_root: "./log/"
data_path: "./processed_data/"
checkpoint_dir: "./saved/xing/"

tau: 1
